DROP DATABASE IF EXISTS kosarkaska_liga;
CREATE DATABASE kosarkaska_liga
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;
USE kosarkaska_liga;

DROP TABLE IF EXISTS NASTUPIO;
DROP TABLE IF EXISTS UTAKMICA;
DROP TABLE IF EXISTS IGRAC;
DROP TABLE IF EXISTS KLUB;

CREATE TABLE KLUB
	(NAZIV_KLUBA CHAR(30),
	DVORANA CHAR(30),
	LOKACIJA CHAR(30),
	PRIMARY KEY (NAZIV_KLUBA))
	ENGINE = INNODB;

CREATE TABLE IGRAC
	(OIB NUMERIC(11) UNSIGNED NOT NULL,
	PREZIME CHAR(20),
	IME CHAR(20),
	DATR DATE,
	VISINA_CM NUMERIC(3) UNSIGNED,
	NAZIV_KLUBA CHAR(30),
	PRIMARY KEY (OIB),
	INDEX IN_IND (NAZIV_KLUBA),
        FOREIGN KEY (NAZIV_KLUBA) REFERENCES KLUB(NAZIV_KLUBA))
	ENGINE = INNODB;

CREATE TABLE UTAKMICA
	(SIFRA CHAR(16),
	DOMACI_KLUB CHAR(30),
	GOSTUJUCI_KLUB CHAR(30),
	DATUM DATE,
	REZULTAT CHAR(7),
	POBJEDNIK CHAR(30),
	PRIMARY KEY (SIFRA),
	INDEX UD_IND (DOMACI_KLUB),
    	INDEX UG_IND (GOSTUJUCI_KLUB),
    	INDEX UP_IND (POBJEDNIK),
    	FOREIGN KEY (DOMACI_KLUB) REFERENCES KLUB(NAZIV_KLUBA),
    	FOREIGN KEY (GOSTUJUCI_KLUB) REFERENCES KLUB(NAZIV_KLUBA),
    	FOREIGN KEY (POBJEDNIK) REFERENCES KLUB(NAZIV_KLUBA))
	ENGINE = INNODB;

CREATE TABLE NASTUPIO
	(OIB NUMERIC(11) UNSIGNED NOT NULL,
	SIFRA CHAR(16),
	POENI NUMERIC(3) UNSIGNED,
	SKOKOVI NUMERIC(3) UNSIGNED,
	ASISTENCIJE NUMERIC(3) UNSIGNED,
	BLOKADE NUMERIC(3) UNSIGNED,
	PRIMARY KEY (OIB, SIFRA),
	INDEX NO_IND (OIB),
    	INDEX NS_IND (SIFRA),
    	FOREIGN KEY (OIB) REFERENCES IGRAC(OIB),
    	FOREIGN KEY (SIFRA) REFERENCES UTAKMICA(SIFRA))
	ENGINE = INNODB;