USE kosarkaska_liga;

SELECT UTAKMICA.SIFRA, KLUB.DVORANA,IGRAC.PREZIME, MAX(POENI) FROM UTAKMICA,KLUB,IGRAC,NASTUPIO WHERE UTAKMICA.SIFRA=NASTUPIO.SIFRA AND UTAKMICA.DOMACI_KLUB=KLUB.NAZIV_KLUBA AND NASTUPIO.OIB=IGRAC.OIB AND NASTUPIO.POENI = (SELECT MAX(POENI) FROM NASTUPIO WHERE NASTUPIO.SIFRA=UTAKMICA.SIFRA) GROUP BY UTAKMICA.SIFRA;

SELECT IGRAC.OIB,PREZIME,IME,AVG(POENI),AVG(SKOKOVI),AVG(ASISTENCIJE),AVG(BLOKADE) FROM IGRAC,NASTUPIO WHERE IGRAC.OIB=NASTUPIO.OIB AND IGRAC.NAZIV_KLUBA='Dallas Mavericks' GROUP BY IGRAC.OIB ORDER BY AVG(POENI) DESC;

SELECT NAZIV_KLUBA,PREZIME,IME, VISINA_CM FROM IGRAC VAR1 WHERE VISINA_CM=(SELECT MAX(VISINA_CM) FROM IGRAC VAR2 WHERE VAR1.NAZIV_KLUBA=VAR2.NAZIV_KLUBA) GROUP BY NAZIV_KLUBA ORDER BY VISINA_CM DESC;

SELECT SIFRA, PREZIME, POENI+SKOKOVI+ASISTENCIJE+BLOKADE MAKS FROM NASTUPIO, IGRAC WHERE NASTUPIO.OIB = IGRAC.OIB AND IGRAC.DATR>'1995-01-01' ORDER BY MAKS DESC LIMIT 5;